### ISSUE TITLE
Running coordmap finder

### ISSUE THREAD

**Issue by jeff-comley** [JanLunge/pog#3]
On the Coordmap setup stage nothing gets filled in.  Opened the code.py in thonny and ran it and get this:

starting keyboard Pico Test Board (01H2BEFRHEMRVMT36SJRKD8P9A)
running coordmap setup
Traceback (most recent call last):
  File "<stdin>", line 42, in <module>
  File "kmk/kmk_keyboard.py", line 472, in go
  File "kmk/kmk_keyboard.py", line 496, in _init
  File "kmk/kmk_keyboard.py", line 336, in _init_matrix
  File "kmk/scanners/keypad.py", line 51, in __init__
TypeError: object of type 'Pin' has no len()

This is on a raspberry pi pico, 4 button test matrix set to 1 row and 4 columns.

**Comment by JanLunge** [comment]
Seems I had Notifications for Issues and PRs off my bad, still wanted to answer here. this was an issue where 1 row was not passed as a list properly this has been fixed a few releases back.
