### ISSUE TITLE
I setup my keyboard but it doesnt work after.

### ISSUE THREAD

**Issue by miraficus** [JanLunge/pog#47]
My keyboard works until CoordMap. When i flash the coord map finder the buttons type 000 001... as expected but when i save and create keyboard layout with keymap the keyboard doesnt type anything. The keyboard is 3x3 macropad with direct pins wiring method. Ihave keymap setup like this for now: [KC.ESC, KC.W, KC.E, KC.A, KC.S, KC.D, KC.Y, KC.X, KC.ENT].

I tried to get some info from the Debug console and this is all it gave me.

```
\[2K[0GAuto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Press any key to enter the REPL. Use CTRL-D to reload.
soft reboot

[2K[0GAuto-reload is on. Simply save files over USB to run them or enter REPL to disable.
[2K[0Gcode.py output:
]0;🐍code.py | 9.2.1\starting keyboard PicoPad (01JD83MTTDKYCERVWQBSD20PBK)
Traceback (most recent call last):
  File "code.py", line 15, in <module>
  File "kb.py", line 25, in __init__
ImportError: no module named 'kmk.modules.oneshot'
]0;🐍25@kb.py ImportError | 9.2.1\
Code done running.

Press any key to enter the REPL. Use CTRL-D to reload
```

I flashed flash_nuke.uf2 and installed circuitpython and kmk again but nothing changed.

**Comment by miraficus** [comment]
I downloaded [older version of KMK](https://github.com/KMKfw/kmk_firmware/tree/9f517d07bb1482c3e69e0faba999f7e8c46f8dda) and the keyboard works.

**Comment by gutomotta** [comment]
Seems like POG is still using a feature (Oneshot) that has been deprecated and removed from newer versions of KMK. You can confirm you have the same issue by following instructions on the "Debug" tab until you see some output from CircuitPython. I managed to see the error reported by the Author after clicking "Exit Repl" (this wasn't clear for me at first, but you have to Exit Repl so that the keyboard code can actually run).

I managed to workaround it by manually changing the `code.py` file. Specifically, I changed the following line:

```python
    keyboard = POGKeyboard(features=pog.kbFeatures)
```

to:

```python
    features = pog.kbFeatures
    features.remove("oneshot")
    keyboard = POGKeyboard(features=features)
```

I noticed that POG is not rewriting `code.py` once you save your config unless you actually remove the file, so you should not lose this fix every time you save your Keymap on POG.

**Comment by JanLunge** [comment]
I just released pog 1.7.0 which now switches the oneshot to sticky keys as they are deprecated. we also now lock to a kmk version so updates should stay compatible with each pog version https://github.com/JanLunge/pog/releases/tag/v1.7.0

**Comment by gutomotta** [comment]
That's awesome, @JanLunge. Thank you so much!
